#!/bin/sh
# novadeck stable per-device Wi-Fi MAC.
#
# The WCN7850 on this SM8650 port has no vendor NVRAM / nvmem MAC path, so the Wi-Fi radio otherwise
# comes up with a fresh, random locally-administered address on every boot — and the SAME address
# across every unit flashed from one image. Routers, DHCP reservations and network identity all expect
# a stable MAC, so we synthesise one: derive a locally-administered UNICAST address from a
# hardware-unique per-unit seed, persist it write-once, and re-apply it every boot.
#
# Bluetooth is handled by its SIBLING, gen-bdaddr.sh — not here, because it is a different problem:
# the BT controller has no address at all and is therefore INVISIBLE, where the Wi-Fi radio works and
# merely needs pinning. It also has to run later (it waits for the controller the QCA setup creates),
# and this unit must stay early and fast for NetworkManager.
#
# An earlier note here claimed a stable BT address was unachievable — "the mgmt interface is
# unreachable until bluetoothd initialises it, and a public-address override is only accepted while it
# is powered off, so the two windows never overlap" (HW 2026-07-07). BOTH HALVES ARE WRONG, and the
# error cost us working Bluetooth for a month: mgmt is a KERNEL socket (AF_BLUETOOTH /
# HCI_CHANNEL_CONTROL) that bluetoothd is merely another client of, and an unconfigured controller sits
# powered-off waiting for exactly that call — the windows overlap permanently. HW-disproved 2026-08-19.
#
# Persistence lands on the writable side (/var/lib), never the root fs: /var stays read-write even
# under the Phase-4 immutable root, and the drop-in is regenerated into /run (tmpfs) each boot, so
# nothing here needs a writable /etc or /usr.
set -eu

STATE=/var/lib/novadeck
NM_RUN=/run/NetworkManager/conf.d
NM_DROPIN="$NM_RUN/00-novadeck-stable-mac.conf"

# --- per-unit seed ------------------------------------------------------------------------------
# machine-id is empty in the shipped image, so systemd writes a fresh RANDOM id on first boot: unique
# per unit and stable across reboots — an ideal seed. Fall back to the Qualcomm SoC serial, then to a
# one-time random value (still persisted below, so it too stays stable thereafter).
seed=$(cat /etc/machine-id 2>/dev/null || true)
[ -n "$seed" ] || seed=$(cat /sys/devices/soc0/serial_number 2>/dev/null || true)
[ -n "$seed" ] || seed=$(head -c16 /dev/urandom | od -An -tx1 | tr -d ' \n')

# Derive a MAC from the seed: sha256 it, take 6 octets, then in the first octet set the
# locally-administered bit (0x02) and clear the multicast bit (0x01) so it is a valid unicast LAA.
h=$(printf '%s-wifi' "$seed" | sha256sum | cut -c1-12)
o1=$(printf '%02x' "$(( (0x$(printf '%s' "$h" | cut -c1-2) | 0x02) & 0xfe ))")
WIFI_MAC="$o1:$(printf '%s' "$h" | cut -c3-4):$(printf '%s' "$h" | cut -c5-6):$(printf '%s' "$h" | cut -c7-8):$(printf '%s' "$h" | cut -c9-10):$(printf '%s' "$h" | cut -c11-12)"

# Write-once: keep the FIRST address ever chosen, so it survives even if the seed ever changes
# (e.g. a machine-id reset).
mkdir -p "$STATE"
if [ -s "$STATE/mac-wifi" ]; then
  WIFI_MAC=$(cat "$STATE/mac-wifi")
else
  ( umask 022; printf '%s\n' "$WIFI_MAC" >"$STATE/mac-wifi" )
fi

# A global [connection] default pins every Wi-Fi/Ethernet profile to our stable address, and
# scan-rand-mac-address=no makes probe requests use it too. Written to /run (tmpfs) so it is
# rebuilt from the persisted address each boot and never touches a RO root.
mkdir -p "$NM_RUN"
cat >"$NM_DROPIN" <<EOF
# Generated by novadeck-macgen.service — see /usr/lib/novadeck/gen-mac.sh.
# The Wi-Fi radio has no persistent hardware MAC on this device, so pin a stable derived one
# instead of relying on a (non-existent) permanent address.
[device]
wifi.scan-rand-mac-address=no

[connection]
wifi.cloned-mac-address=$WIFI_MAC
ethernet.cloned-mac-address=$WIFI_MAC
EOF
echo "[novadeck-macgen] Wi-Fi MAC $WIFI_MAC -> $NM_DROPIN"
