#!/usr/bin/env bash
# Offline test for the removable-storage surface — the pieces that let an SD card be adopted as a
# Steam library (issue #42).
#
#   tests/test-storage.sh
#
# WHY THIS FILE EXISTS. The whole surface is declarations: a package name in a list, a lock row, a
# polkit rule granting some action ids and — the part that matters — deliberately NOT granting
# others. None of that fails loudly when it drifts. A package added to PKGS but never relocked
# ships nothing; a rule that grows a format action before anything refuses formatting the boot disk
# is a card-shaped hole in the running system. Both are exactly the shape rootfs/guard-rootfs.sh
# exists for on the built tree, and both are checkable here, on the sources, in milliseconds.
#
# WHAT THIS CANNOT COVER: whether udisksd actually answers, whether the client's Storage page
# enumerates anything, and whether an inserted card mounts. Those need a device with a spare card,
# which is what internal installation made possible — see the checklist on #42.
set -uo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PKGSRC="$ROOT/rootfs/customize-base.sh"
LOCK="$ROOT/rootfs/manifest.lock"
RULES="$ROOT/rootfs/overlay/usr/share/polkit-1/rules.d/50-novadeck-storage.rules"

PASS=0; FAIL=0; CASE=""
ok()  { PASS=$((PASS+1)); printf '  ok   %s -- %s\n' "$CASE" "$1"; }
bad() { FAIL=$((FAIL+1)); printf '  FAIL %s -- %s\n' "$CASE" "$1"; }

# =================================================================================================
CASE="udisks2-is-declared-and-locked"
# THE PAIR, not either half. PKGS is the declaration and manifest.lock is what the base actually
# installs, and they are regenerated by different commands (`make relock`). A PKGS entry with no
# lock row is a package the image does not have, which is precisely the state that made Settings >
# Storage enumerate nothing in the first place.
for p in udisks2 f3; do
  grep -qE "[( ]$p[) ]" "$PKGSRC" \
    && ok "$p is in PKGS" \
    || bad "$p is not declared in ${PKGSRC#"$ROOT"/}"
  grep -qE "^$p " "$LOCK" \
    && ok "$p has a row in manifest.lock (the base really installs it)" \
    || bad "no $p row in ${LOCK#"$ROOT"/} — declared but never relocked, so the image ships nothing"
done

# f3 is not in any repo we consume (it is an AUR package), so it can only come from the overlay —
# and an overlay package is a source.pin plus the PKGBUILD it names. A PKGS entry with neither is a
# package the resolver cannot find at all.
[ -f "$ROOT/packages/f3/source.pin" ] && [ -f "$ROOT/packages/f3/PKGBUILD" ] \
  && ok "f3 has an overlay source.pin and a local PKGBUILD" \
  || bad "f3 is in PKGS with no overlay package to build it from"
grep -q 'build/f3probe' "$ROOT/packages/f3/PKGBUILD" \
  && ok "and builds only f3probe (f3fix is what would drag parted onto the image)" \
  || bad "the PKGBUILD builds more than f3probe — check what it links before accepting that"

# =================================================================================================
CASE="storage-polkit-rule"
[ -f "$RULES" ] && ok "the rule ships" || bad "missing: ${RULES#"$ROOT"/}"

# The gate, not just the grants. Without the active+wheel test the rule would authorize any subject
# that can reach the bus, including a non-session one.
grep -q 'subject.active' "$RULES" && grep -q 'isInGroup("wheel")' "$RULES" \
  && ok "gated on an active session in wheel, like 50-novadeck-timezone.rules" \
  || bad "the rule does not gate on subject.active + wheel"

# THE QUOTED STRINGS WITH THE COMMENTS STRIPPED, never a grep over the whole file. This rule
# NAMES the actions it deliberately withholds, in prose, immediately above the ones it grants — so
# a plain grep answers "is this word in the file", which is yes for both halves and is how the
# negative case below would pass while asserting nothing.
granted() { sed 's,//.*,,' "$RULES" | grep -oE '"[A-Za-z0-9._-]+"' | tr -d '"'; }

for act in filesystem-unmount-others eject-media eject-media-other-seat \
           power-off-drive power-off-drive-other-seat; do
  granted | grep -qx "org.freedesktop.udisks2.$act" \
    && ok "grants $act" \
    || bad "does not grant $act — the client's release path fails with a silent bus refusal"
done

# =================================================================================================
CASE="nothing-that-writes-a-device-is-granted"
# THE REFUSALS LIVE IN THE HELPER, so the bus must not offer a way around them. format-device.sh
# checks that a disk is a removable SD this system is not running from before it writes anything,
# and granting the shell org.freedesktop.udisks2.format-device or modify-device would let the client
# repartition a disk through udisks directly with none of that applied.
#
# The reason this case was FIRST written is spent — "nothing refuses formatting the boot disk yet"
# was true then and is not now — but the grant is still wrong, for the reason above.
#
# filesystem-mount is absent for a different reason and is NOT a defect: stock udisks2 policy
# already allows it for an active session, so listing it would make this file claim to do something
# it does not do.
for act in modify-device format-device run-steamos-polkit-helpers-steamos-format-sdcard \
           run-steamos-polkit-helpers-steamos-format-device; do
  granted | grep -q -- "$act" \
    && bad "$act is granted — see #42: nothing refuses formatting the boot disk yet" \
    || ok "$act is not granted"
done

# =================================================================================================
CASE="rule-is-syntactically-whole"
# Not a JS parser — a brace/bracket balance and a terminator. A truncated polkit rule does not fail
# loudly: polkitd logs a parse error to the journal and CARRIES ON with the rule absent, which
# reads on the device as "the grant silently does not work".
awk '{o+=gsub(/[{[]/,"&"); c+=gsub(/[}\]]/,"&")} END{exit !(o==c && o>0)}' "$RULES" \
  && ok "braces and brackets balance" \
  || bad "unbalanced braces/brackets — polkitd would drop the whole rule with only a journal line"
grep -q '^});' "$RULES" \
  && ok "addRule() is closed" \
  || bad "the addRule() call is not terminated"

# =================================================================================================
CASE="the-scripts-ship-and-parse"
LIB="$ROOT/rootfs/overlay/usr/lib/novadeck/storage/lib-storage.sh"
FMT="$ROOT/rootfs/overlay/usr/lib/novadeck/storage/format-device.sh"
AUTO="$ROOT/rootfs/overlay/usr/lib/novadeck/storage/automount.sh"
EVT="$ROOT/rootfs/overlay/usr/lib/novadeck/storage/block-event.sh"
POLICY="$ROOT/rootfs/overlay/usr/share/polkit-1/actions/org.novadeck.policykit.storage.policy"
UDEV="$ROOT/rootfs/overlay/usr/lib/udev/rules.d/99-novadeck-automount.rules"
UNIT="$ROOT/rootfs/overlay/usr/lib/systemd/system/novadeck-automount@.service"
H_SD="$ROOT/rootfs/overlay/usr/bin/steamos-polkit-helpers/steamos-format-sdcard"
H_DEV="$ROOT/rootfs/overlay/usr/bin/steamos-polkit-helpers/steamos-format-device"

# EVERY HELPER THE CLIENT CAN RUN LEAVES A LINE. pkexec records what it EXECUTED, so a call it
# declines leaves nothing, and steamos-update is not pkexec'd at all — so an invocation of it was
# invisible. "The client never called us" and "the client called us and it went nowhere" then look
# identical from the device, which is exactly the ambiguity that stalled the validation question.
for h in "$H_SD" "$H_DEV" "$ROOT/rootfs/overlay/usr/bin/steamos-polkit-helpers/steamos-update"; do
  grep -q 'logger -t' "$h" \
    && ok "$(basename "$h") records its own invocation" \
    || bad "$(basename "$h") runs silently — a call to it cannot be distinguished from no call"
done

for f in "$LIB" "$FMT" "$AUTO" "$EVT" "$H_SD" "$H_DEV"; do
  n="${f#"$ROOT"/}"
  [ -f "$f" ] || { bad "missing: $n"; continue; }
  bash -n "$f" 2>/dev/null && ok "$(basename "$f") parses" || bad "$n is not valid bash"
  # THE EXEC BIT IS PART OF THE ARTIFACT. The overlay is copied with its modes, and a script that
  # ships 0644 fails at the moment udev or the client runs it — the OOBE black screen was exactly
  # this, a lost exec bit that nothing checked.
  [ -x "$f" ] && ok "$(basename "$f") is executable" || bad "$n is not executable"
done
for f in "$POLICY" "$UDEV" "$UNIT"; do
  [ -f "$f" ] && ok "$(basename "$f") ships" || bad "missing: ${f#"$ROOT"/}"
done

# =================================================================================================
CASE="pkexec-action-matches-the-script"
# THE HIGHEST-VALUE ASSERTION IN THIS FILE. pkexec picks the action whose exec.path annotation
# equals the program being run; if the annotation and the helper's target ever drift apart, pkexec
# silently falls back to org.freedesktop.policykit.exec, which is auth_admin. On a device where no
# account has a password that is not a prompt — it is a Format button that does nothing, with no
# error anywhere. A string comparison here is the only thing that catches it.
annot="$(sed -n 's/.*exec\.path">\([^<]*\)<.*/\1/p' "$POLICY" | head -1)"
target="$(sed -n 's/.*pkexec \([^ ]*format-device\.sh\).*/\1/p' "$H_SD" | head -1)"
[ -n "$annot" ] && [ "$annot" = "$target" ] \
  && ok "the action annotates exactly what the helper execs ($annot)" \
  || bad "annotation '$annot' != helper target '$target' — pkexec would fall back to auth_admin"
[ "$annot" = "/usr/lib/novadeck/storage/format-device.sh" ] \
  && ok "and that is the shipped path" \
  || bad "the annotated path is not where the script ships"
grep -q "<allow_active>yes</allow_active>" "$POLICY" \
  && ok "allow_active=yes (the seat session may format)" \
  || bad "allow_active is not yes — the seat session could not format"
grep -q "<allow_inactive>no</allow_inactive>" "$POLICY" && grep -q "<allow_any>no</allow_any>" "$POLICY" \
  && ok "inactive and any are refused (an SSH login cannot wipe a card)" \
  || bad "allow_inactive/allow_any are not both no"

# =================================================================================================
CASE="both-paths-apply-the-same-refusals"
# The formatter and the mounter must agree about what a card is. They share lib-storage.sh for
# exactly that reason, and this asserts neither has grown its own answer.
for f in "$FMT" "$AUTO"; do
  n="$(basename "$f")"
  grep -q 'storage_is_sd' "$f" && grep -q 'storage_is_system_disk' "$f" \
    && ok "$n applies both predicates" \
    || bad "$n does not apply the SD + system-disk predicates"
  grep -q 'lib-storage.sh' "$f" \
    && ok "$n sources the shared library" \
    || bad "$n does not source lib-storage.sh — a second copy of the predicates"
done

# =================================================================================================
CASE="unknown-boot-disk-refuses"
# THE FAIL-CLOSED DIRECTION, and the one that is easy to get backwards. usr/lib/novadeck/on-boot-disk
# fails OPEN when /run/novadeck/boot is missing, because a single-disk device must still mount its
# own /home. Here the same absence has to mean "assume it IS the system disk", or a degraded
# initramfs turns into an erased card. Run against a sandbox where the file cannot exist.
W="$(mktemp -d)"; trap 'rm -rf "$W"' EXIT

# THE HANDOFF IS key=value, NOT A PATH — the whole reason this case exists. Reading the file as a
# device node made storage_boot_disk answer "unknown" for every device, which the old
# short-circuit then turned into "this card is system storage". HW-caught 2026-09-02 on an
# internally-installed device: `automount.sh: skipping /dev/mmcblk0p1: this system runs from it`.
# The stub for storage_disk_of stands in for block devices this host does not have.
printf 'slot=A\nsource=grub\nroot=/dev/mmcblk9p4\nvar=/dev/mmcblk9p6\n' >"$W/boot"
out="$(NOVADECK_BOOTINFO="$W/boot" bash -c '
  . '"$LIB"'
  storage_disk_of() { printf "%s\n" "${1##*/}" | sed "s/p[0-9]*$//"; }
  storage_boot_disk' 2>/dev/null | tail -1)"
[ "$out" = mmcblk9 ] \
  && ok "root= is parsed out of the key=value handoff (mmcblk9p4 -> mmcblk9)" \
  || bad "the handoff resolved to '$out', expected mmcblk9 — the file is key=value, not a path"

# The seam name must be the one on-boot-disk already uses, or the two files disagree about where
# the boot disk is written down.
grep -q 'NOVADECK_BOOTINFO' "$LIB" && grep -q 'NOVADECK_BOOTINFO' "$ROOT/rootfs/overlay/usr/lib/novadeck/on-boot-disk" \
  && ok "both readers use the NOVADECK_BOOTINFO seam" \
  || bad "the seam name does not match on-boot-disk's"

# Fail-closed, but only when NOTHING resolves: no handoff AND a mount table that answers nothing.
# findmnt is stubbed to silence rather than removed from PATH — bash substitutes a default PATH when
# the environment has none, so `env -i` does NOT stop it running, and a first attempt at this case
# passed against the HOST's real mounts while asserting nothing.
out="$(NOVADECK_BOOTINFO=/nonexistent bash -c '
  . '"$LIB"'
  findmnt() { :; }
  storage_is_system_disk mmcblk9 && echo REFUSED || echo ALLOWED' 2>/dev/null | tail -1)"
[ "$out" = REFUSED ] \
  && ok "nothing resolvable at all -> treated as the system disk" \
  || bad "answered '$out' with no handoff and no mount table — that must fail closed"

# And the case the first version got wrong: no handoff, but a mount table that plainly says the
# system runs from another disk. That card is eligible.
out="$(NOVADECK_BOOTINFO=/nonexistent bash -c '
  . '"$LIB"'
  findmnt() { case "$*" in *--target\ /) echo /dev/sda15 ;; *) echo /dev/sda19 ;; esac; }
  storage_disk_of() { printf "%s\n" "${1##*/}" | sed -e "s/p[0-9]*$//" -e "s/[0-9]*$//"; }
  storage_is_system_disk mmcblk9 && echo REFUSED || echo ALLOWED' 2>/dev/null | tail -1)"
[ "$out" = ALLOWED ] \
  && ok "a missing handoff does not condemn a card the mount table clears" \
  || bad "answered '$out' — a card is being refused because one optional hint is absent"

# =================================================================================================
CASE="mounted-detection-actually-works"
# BEHAVIOURAL, not a grep, because the grep version of this suite passed while the predicate was
# inverted. The original implementation piped a while-loop into `grep -q`; with set -euo pipefail
# the early-exiting grep SIGPIPEs the loop and pipefail reports failure, so "something is mounted"
# came back as "nothing is mounted" — the one answer that matters. It wiped a card on 2026-09-02.
mounted_says() { # <stub findmnt output> -> MOUNTED|CLEAR
  NOVADECK_BOOTINFO=/nonexistent bash -c '
    set -euo pipefail
    . '"$LIB"'
    findmnt() { printf "%s\n" "'"$1"'"; }
    storage_disk_of() { printf "%s\n" "${1##*/}" | sed -e "s/p[0-9]*$//"; }
    storage_is_mounted mmcblk0 && echo MOUNTED || echo CLEAR' 2>/dev/null | tail -1
}
[ "$(mounted_says /dev/mmcblk0p1)" = MOUNTED ] \
  && ok "a mounted partition of the disk is detected" \
  || bad "storage_is_mounted said CLEAR for a mounted card — the inverted-predicate bug is back"
[ "$(mounted_says /dev/sda19)" = CLEAR ] \
  && ok "a mount on another disk is not confused for this one" \
  || bad "storage_is_mounted claimed a foreign mount belongs to this disk"
# set -e must not be able to kill the caller on the CLEAR path either: the formatter runs under
# `set -e` and calls this in a plain statement.
[ "$(mounted_says '')" = CLEAR ] \
  && ok "an empty mount table answers CLEAR without aborting the caller" \
  || bad "an empty mount table did not answer CLEAR"

# =================================================================================================
CASE="format-unmounts-before-it-wipes"
# The refusal was replaced by an unmount, because a card is ALWAYS mounted by our own automount by
# the time anyone asks to format it — "refuse if mounted" was unreachable in practice and left
# nothing guarding wipefs. Order matters: the unmount has to precede the first destructive command.
# CODE LINES ONLY — both words appear in the comments explaining why this order exists, and a
# comment matched first is how this case failed on a file that was already correct.
u=$(grep -nE '^[^#]*umount "\$mnt"' "$FMT" | head -1 | cut -d: -f1)
w=$(grep -nE '^[^#]*wipefs' "$FMT" | head -1 | cut -d: -f1)
[ -n "$u" ] && [ -n "$w" ] && [ "$u" -lt "$w" ] \
  && ok "unmount (line $u) runs before the first wipefs (line $w)" \
  || bad "wipefs is not preceded by the unmount loop — signatures can be erased under a live mount"
grep -q 'refusing to erase a filesystem still in use' "$FMT" \
  && ok "a failed unmount is fatal" || bad "a failed unmount does not abort the format"
grep -q 'storage_is_mounted "\$DISK" && die' "$FMT" \
  && ok "and a still-mounted disk is refused after the unmount pass" \
  || bad "nothing re-checks the disk after unmounting"

# =================================================================================================
CASE="the-mounter-does-not-announce-to-the-client"
# THE MOUNTER MOUNTS; IT DOES NOT ADOPT. steam://addlibraryfolder was added while the missing
# Format action was unexplained, and it does more than tell the client something — adding a library
# folder CREATES a SteamLibrary on the card, so every card ever inserted became a Steam library,
# including one belonging to another system. A mounted card with no library is supposed to appear
# as a drive that OFFERS to be formatted; announcing it silently converted that case into the other
# one. The client enumerates over UDisks2 unaided (GetPotentialFolders returns the card), and the
# whole Settings > Storage story was exercised on hardware with this code not running.
# CODE LINES ONLY. The comment that replaced it explains what was removed and names the URL to do
# so, and a whole-file grep matches that prose — the fourth time in this suite that a comment has
# failed a correct file. Strip comments before asserting about code.
code() { sed 's,#.*,,' "$1"; }
code "$AUTO" | grep -q 'addlibraryfolder' \
  && bad "the mounter announces to the client again — that creates a library on every inserted card" \
  || ok "no steam://addlibraryfolder: mounting a card does not make it a library"
code "$AUTO" | grep -qE 'systemd-escape|urllib\.parse\.quote|systemd-run' \
  && bad "the announce machinery is back in code (escaping, encoding or systemd-run)" \
  || ok "and none of the machinery it needed survives"

# =================================================================================================
CASE="udev-rule-is-narrow"
# THIS LINE HAS BEEN WRONG IN BOTH DIRECTIONS, so the suite now pins the direction that survives
# both cases. Matching `change` mounts a freshly formatted card (its signature arrives as a change),
# and it ALSO remounts a card the instant anyone unmounts it — the kernel emits a change on close of
# a writable block device, which is what an unmount is. That made the client's Unmount useless
# (HW-caught 2026-09-03). The format case moved into the formatter, which knows what it just did.
grep -q 'ACTION!="add|remove"' "$UDEV" \
  && ok "acts on add|remove only (a change is also what an unmount looks like)" \
  || bad "the rule acts on change — every unmount will remount the card and Eject cannot work"
grep -q 'ACTION!="add|change|remove"' "$UDEV" \
  && bad "change is matched again — this is the regression that broke Unmount" \
  || ok "and change specifically is not matched"
code "$FMT" | grep -q '/usr/lib/novadeck/storage/automount.sh add' \
  && ok "the formatter mounts the card itself, which is what matching change used to buy" \
  || bad "nothing mounts a freshly formatted card — the case that put change in the rule is back"
# FATAL, not best-effort, and upstream's own helper is the authority: `exit 5` on a failed
# post-format mount. The client has a string for it — "formatted correctly, but it failed to mount
# with the system running. A reboot is required" — which is never shown if the code is swallowed.
code "$FMT" | grep -q 'but it could not be mounted" 5' \
  && ok "a failed post-format mount exits 5, which is how the user is told to reboot" \
  || bad "the post-format mount failure is swallowed — the client cannot report it"
grep -q 'KERNEL!="mmcblk\*p\*"' "$UDEV" \
  && ok "matches SD/MMC partitions only" \
  || bad "the rule does not restrict to mmcblk*p*"
grep -qE 'KERNEL=="?sd\*|sd\[a-z\]' "$UDEV" \
  && bad "the rule matches sd* — that is the internal UFS on this hardware, not removable media" \
  || ok "does not match sd* (the vendor's internal storage)"
grep -q 'novadeck-automount@%k.service' "$UDEV" \
  && ok "hands the work to the templated unit" \
  || bad "the rule does not start novadeck-automount@%k.service"
grep -q 'ExecStart=/usr/lib/novadeck/storage/block-event.sh add %i' "$UNIT" \
  && ok "the unit runs the shipped automount path" \
  || bad "the unit's ExecStart does not match the shipped script"

# THE COLD-BOOT CASE, which the hotplug case hides. Mounting is a D-Bus call to a bus-activated
# service, so it needs a BUS — and with DefaultDependencies=no and no ordering, a card already in
# the slot at power-on fired this ~8s before dbus-broker was ready. busctl never reached udisks:
# failed unit, unmounted card, every boot with a card in (HW-caught 2026-09-03).
grep -qE '^After=.*dbus\.socket' "$UNIT" \
  && ok "ordered After=dbus.socket (a bus-activated call needs a bus first)" \
  || bad "no After=dbus.socket — at cold boot this runs before dbus-broker and cannot mount"
grep -qE '^Wants=.*dbus\.socket' "$UNIT" \
  && ok "and Wants= it, so the socket is in the transaction rather than merely ordered against" \
  || bad "After= without Wants= — ordering against a unit nothing pulled in is not ordering"

# =================================================================================================
CASE="a-mount-failure-names-its-own-reason"
# The failure above reported "udisks refused to mount", which was false: udisks never saw the call.
# stderr was folded into the stdout pipe and sed away, so every distinct failure — no bus, no such
# object, a polkit refusal — arrived as the same wrong sentence.
grep -q "log \"udisks refused to mount" "$AUTO" \
  && bad "the old blanket message is back — it names udisks for failures udisks never saw" \
  || ok "the failure path no longer blames udisks for everything"
code "$AUTO" | grep -q '2>"\$err"' \
  && ok "busctl's stderr is captured instead of folded into the mountpoint pipe" \
  || bad "stderr is not captured separately — the reason is discarded before it can be logged"
code "$AUTO" | grep -q 'could not mount \$DEVICE: \${reason' \
  && ok "and the captured reason is what gets logged" \
  || bad "the captured stderr is never logged"

# =================================================================================================
CASE="only-ext4-is-automounted"
# Upstream's reason, verbatim: "We need symlinks for Steam for now, so only automount ext4 as that's
# what Steam will format". A vfat or exfat card cannot host a library — no symlinks, no casefolding
# — and mounting one gives the user a mount they cannot use in the exact place the client is trying
# to tell them the card needs formatting.
code "$AUTO" | grep -q 'FSTYPE' \
  && ok "the mounter reads the filesystem type before mounting" \
  || bad "nothing checks the filesystem type — any card mounts"
code "$AUTO" | grep -q '"\$FSTYPE" != ext4' \
  && ok "and refuses anything that is not ext4" \
  || bad "the ext4 restriction is not applied"
# EXIT 0, where upstream exits 2: inserting a foreign card is normal, and a non-zero exit here
# leaves a failed unit for the rest of the boot.
sed -n '/not ext4 — a Steam library/,+1p' "$AUTO" | grep -q 'exit 0' \
  && ok "and stands down with exit 0 rather than leaving a failed unit" \
  || bad "a foreign card leaves a failed unit — that is a fault report for a normal action"

# =================================================================================================
CASE="one-lock-keeps-the-formatter-and-the-mounter-apart"
# MEASURED, after two rounds of treating the symptom. During a validated format the mounter ran
# twice on the device being formatted — once before the partition existed, once while mkfs was
# writing it ("fsconfig() failed: Can't open blockdev"). Both processes owned one device. Upstream
# takes a shared flock in both paths for exactly this; we had none.
code "$LIB" | grep -q 'storage_lock()' \
  && ok "there is one lock helper, shared by both scripts" \
  || bad "no storage_lock — nothing stops a format and an automount running together"
code "$LIB" | grep -q 'flock -n 9' \
  && ok "and it is non-blocking, so a caller that cannot have it moves on" \
  || bad "the lock blocks — a udev-triggered unit would wait instead of standing down"
code "$FMT" | grep -q 'storage_lock "\$PARTBASE"' \
  && ok "the formatter takes it" || bad "the formatter does not take the lock"
code "$EVT" | grep -q 'storage_lock "\$DEVBASE"' \
  && ok "the udev entry point takes it too" || bad "the udev entry point does not take the lock"
# EXIT 0, not a failure: a format in progress is a reason not to mount, and the formatter mounts the
# card itself when it is done. A non-zero exit here is a failed unit for a healthy system.
sed -n '/a format is in progress/,+1p' "$EVT" | grep -q 'exit 0' \
  && ok "and stands down with exit 0, not a failed unit" \
  || bad "the mounter reports failure when it merely stood aside"
# ORDER: the lock must precede the first thing that touches the device, which is the unmount pass.
l_ln=$(grep -nE '^storage_lock "\$PARTBASE"' "$FMT" | head -1 | cut -d: -f1)
u_ln=$(grep -nE '^[^#]*umount "\$mnt"' "$FMT" | head -1 | cut -d: -f1)
[ -n "$l_ln" ] && [ -n "$u_ln" ] && [ "$l_ln" -lt "$u_ln" ] \
  && ok "taken (line $l_ln) before the first thing that touches the device (line $u_ln)" \
  || bad "the lock is taken after the device is already being worked on"

# BEHAVIOURAL, because a lock that does not exclude is worse than none: it reads as protection.
# Held in one process, attempted in another, against a sandbox /run.
# The first version of this case reported HELD/FREE from both the outer and inner shell, so "the
# parent could not take the lock" and "the child took it as well" were the same string — it failed
# against a lock that works. Each side now names itself, and both are asserted.
sed "s,/run/novadeck,$W/run/novadeck,g" "$LIB" > "$W/lib.sh"
lock_out="$(bash -c '. '"$W/lib.sh"'
    if storage_lock testpart; then
        echo PARENT_ACQUIRED
        bash -c ". '"$W/lib.sh"'; storage_lock testpart && echo CHILD_ACQUIRED || echo CHILD_REFUSED"
    else
        echo PARENT_FAILED
    fi' 2>/dev/null)"
case "$lock_out" in
  *PARENT_ACQUIRED*CHILD_REFUSED*) ok "a second holder is refused while the first has it" ;;
  *PARENT_ACQUIRED*CHILD_ACQUIRED*) bad "storage_lock does not exclude — it reads as protection while providing none" ;;
  *) bad "storage_lock could not be taken at all in the sandbox ($lock_out) — the case proves nothing" ;;
esac
seam="$(bash -c 'NOVADECK_STORAGE_LOCK_HELD=testpart; . '"$W/lib.sh"'; storage_lock testpart && echo PASS || echo BLOCKED' 2>/dev/null | tail -1)"
[ "$seam" = PASS ] \
  && ok "and the parent-holds-it seam lets the formatter's own child through" \
  || bad "the seam does not work — the formatter's post-format mount would be refused"

# =================================================================================================
CASE="the-probes-garbage-is-cleared-where-it-is-made"
# Upstream zeroes the first sectors right after the probe, and its reason stands on its own:
# "Otherwise parted may think we have existing partitions in a bogus state". f3probe --destructive
# writes across the whole device, so what it leaves behind can read as a partition table to whatever
# looks next.
#
# IT IS NOT WHAT FIXED THE FAILED UNIT AFTER EVERY FORMAT. That was the missing lock, established
# afterwards by measurement. This was the second of three attempts at that symptom, and it survives
# only because upstream does it for a reason of its own. The retry it replaced does not survive.
code "$FMT" | grep -qE 'dd if=/dev/zero of="\$DEVICE" bs=512 count=1024' \
  && ok "the formatter zeroes the sectors f3probe scribbled on" \
  || bad "f3probe's garbage is left in place — udev will read it as a filesystem"
probe_ln=$(grep -nE '^ *probe_out=' "$FMT" | head -1 | cut -d: -f1)
dd_ln=$(grep -nE '^ *dd if=/dev/zero' "$FMT" | head -1 | cut -d: -f1)
wipe_ln=$(grep -nE '^[^#]*wipefs' "$FMT" | head -1 | cut -d: -f1)
[ -n "$probe_ln" ] && [ -n "$dd_ln" ] && [ -n "$wipe_ln" ] && [ "$probe_ln" -lt "$dd_ln" ] && [ "$dd_ln" -lt "$wipe_ln" ] \
  && ok "and does it between the probe (line $probe_ln) and the first wipefs (line $wipe_ln)" \
  || bad "the zeroing is not between the probe and the format — that ordering is the whole point"
# NO RETRY IN THE MOUNTER. It was there for this symptom; a failure now names its own reason and
# fails, which is what makes the next unexplained one findable instead of merely quiet.
code "$AUTO" | grep -qE 'tries|sleep 0\.5' \
  && bad "the mount retry is back — it existed only to mask f3probe's leftovers" \
  || ok "the mounter makes one call and reports what it got"

# =================================================================================================
CASE="format-recipe-is-the-one-the-client-needs"
# ext4 + casefold is not a preference: Proton resolves mixed-case Windows paths literally, and a
# card without casefold installs games that then cannot find their own files. -m 0 because a game
# library has no reason to reserve 5%. The owner is deck or the card mounts unwritable.
grep -q 'mkfs\.ext4 .*-O casefold' "$FMT" \
  && ok "mkfs.ext4 -O casefold" || bad "the format is not ext4+casefold"
grep -q 'mkfs\.ext4 .*-m 0' "$FMT" \
  && ok "no reserved blocks (-m 0)" || bad "-m 0 is missing"
grep -q 'OWNER="1000:1000"' "$FMT" \
  && ok "the card ends up owned by deck" || bad "no default owner — the card would mount root-owned"
grep -q 'label: gpt' "$FMT" \
  && ok "GPT with a single partition" || bad "no GPT table is written"

# =================================================================================================
CASE="the-manager-does-not-speak-Storage1"
MGR="$ROOT/rootfs/overlay/usr/bin/novadeck-steamos-manager"
# WE IMPLEMENTED THIS INTERFACE FAITHFULLY AND NOTHING EVER CALLED IT. Storage1 + Job1 were copied
# from Valve's own steamos-manager on the theory that Settings > Storage formats cards through this
# bus name. With every unhandled method logged with its arguments, the client's call count was ZERO
# on hardware; its format path is internal (a native StorageDeviceManager in steamui.so) and execs
# the polkit helper directly — visible in pkexec's own journal line, 2026-09-03.
#
# The assertions are inverted rather than deleted because the interface is plausible: it is Valve's,
# it is in their source, and it looks exactly like the thing a missing Format action would need. It
# came back once already in this branch's history. If it is ever wanted again, it needs a caller
# first, and a caller of ours can use the helper without any of this.
grep -q 'SteamOSManager1\.Storage1' "$MGR" \
  && bad "Storage1 is back — nothing on this device has ever called it" \
  || ok "no Storage1: the client formats through the polkit helper, not this bus name"
python3 -m py_compile "$MGR" 2>/dev/null \
  && ok "and the manager still compiles with all of it removed" \
  || bad "the manager does not compile — the removal left a dangling reference"

# =================================================================================================
CASE="the-session-opens-the-clients-storage-gate"
# THE ONE THAT COST THE MOST TO FIND. Everything else in this file is about being ready to answer
# the client; these two exports are what make it ASK. steamui.so reads them once at startup and
# reports them to the shell as is_adopt_supported / is_unmount_supported, and Settings > Storage
# draws `Format Drive` and `Unmount` only if they are set — before any helper, polkit action or
# D-Bus interface is consulted. Without them the whole surface below is unreachable, silently.
# CODE LINES ONLY: both names appear in the prose that explains them.
STEAMSH="$ROOT/rootfs/overlay/usr/bin/novadeck-steam"
for v in STEAM_ALLOW_DRIVE_ADOPT STEAM_ALLOW_DRIVE_UNMOUNT; do
  sed 's,#.*,,' "$STEAMSH" | grep -qE "^[[:space:]]*export $v=1" \
    && ok "$v=1 is exported into the client's environment" \
    || bad "$v is not exported — the client will not draw the action it gates"
done

# =================================================================================================
CASE="the-formatter-speaks-the-clients-argument-vocabulary"
# The client builds the command line itself (steamui.so: `--device <dev> --label '<name>' --force`,
# plus --enable-duplicate-detection when "Run validation tests" is ticked, which for SD media is
# ticked BY DEFAULT). The parser used to `die "unknown argument"` on all three, so the first format
# the client ever attempted would have failed on --force alone — with the env gate above now open,
# that is a live path rather than a hypothetical one.
# BEHAVIOURAL, against a copy whose absolute source line points at the repo, because the exit code
# is the whole assertion: 22 is "I do not understand you", and anything else means we parsed it.
FCOPY="$W/format-device.sh"
sed "s,^\. /usr/lib/novadeck/storage/lib-storage.sh,. $LIB," "$FMT" > "$FCOPY"; chmod +x "$FCOPY"
arg_exit() { NOVADECK_BOOTINFO=/nonexistent "$FCOPY" "$@" >/dev/null 2>&1; echo $?; }

# /dev/null is a CHARACTER device, so a root run stops at the block-device check and a non-root run
# stops at the root check. Neither writes anything, and neither is 22.
for a in --force --skip-validation --full --quick; do
  [ "$(arg_exit "$a" --device /dev/null)" != 22 ] \
    && ok "$a is accepted" \
    || bad "$a is rejected as an unknown argument — a format sending it would fail on its first try"
done
[ "$(arg_exit --version)" = 0 ] \
  && ok "--version answers, so a caller can tell what this understands" \
  || bad "--version is not answered"
[ "$(arg_exit --no-such-flag)" = 22 ] \
  && ok "and an argument we really do not know is still refused" \
  || bad "an unknown argument no longer refuses — the parser accepts anything"

# THE OPTION SET IS UPSTREAM'S, WITH NOTHING ADDED. A helper whose CLI matches the one it was ported
# from can be diffed against it in one glance; every option we bolt on is one the comparison no
# longer makes. --auto lived here and moved to steamos-format-sdcard, where our divergence belongs.
opts="$(sed -n 's/^ *\(--[a-z|-]*\)).*/\1/p' "$FMT" | tr '|' '\n' | grep -c .)"
for o in --version --force --skip-validation --full --quick --owner --device --label; do
  sed -n 's/^ *\(--[a-z|-]*\)).*/\1/p' "$FMT" | tr '|' '\n' | grep -qx -- "$o" \
    && ok "handles $o, as upstream does" \
    || bad "$o is missing — upstream's getopt has it"
done
[ "$opts" = 8 ] \
  && ok "and handles nothing else (8 long options, upstream's exact set)" \
  || bad "$opts long options handled, upstream has 8 — something was added to a copied contract"

# =================================================================================================
CASE="which-card-is-resolved-in-our-wrapper"
# Upstream's format-sdcard.sh is one line: --device /dev/mmcblk0, because on a Deck the slot always
# is that. Here eMMC also enumerates as mmcblk and a device can be RUNNING FROM a card, so the
# no-argument entry point has to resolve which card it means — and that divergence lives in our
# wrapper rather than as an extra option on the ported helper.
code "$H_SD" | grep -q 'storage_target_sd' \
  && ok "steamos-format-sdcard resolves the card itself" \
  || bad "nothing resolves which card the no-device entry point means"
code "$H_SD" | grep -q 'format-device.sh --device' \
  && ok "and hands the helper an explicit --device" \
  || bad "the wrapper does not pass --device"

# =================================================================================================
CASE="validation-is-on-unless-the-caller-opts-out"
# THE DIRECTION IS THE WHOLE ASSERTION, and it shipped inverted. The client does not ask for the
# test — it asks to SKIP it — so "Run validation tests" ticked sends NO flag at all, and a helper
# that defaults validation off tests nothing precisely when the user asked for it. Verified against
# the upstream helper's own getopt: RUN_VALIDATION=1, --force and --skip-validation set it to 0.
code "$FMT" | grep -qE '^VALIDATE=1' \
  && ok "validation defaults ON, so a ticked box with no flags still runs the test" \
  || bad "validation is opt-in — the client never opts in, so the checkbox would do nothing"
code "$FMT" | grep -qE '\-\-force\|--skip-validation\) VALIDATE=0' \
  && ok "and --force/--skip-validation are what turn it off" \
  || bad "--force does not disable validation — that is what it means upstream"

# f3probe's exit code IS the verdict: `return fake_type == FKTY_GOOD ? 0 : 100 + fake_type`. An
# earlier version of this suite asserted the opposite — that f3probe always exits 0 and the answer
# had to be parsed out of stdout — on a reading that stopped at the printf switch before the return.
code "$FMT" | grep -q 'probe_rc' \
  && ok "the verdict is f3probe's exit code" \
  || bad "the exit code is not consulted"
code "$FMT" | grep -q 'failed the counterfeit test' \
  && ok "and a card that fails is refused rather than formatted" \
  || bad "a failed probe does not refuse the format"
# CODE LINES ONLY — the comment above the probe names f3fix in order to explain what we do NOT do,
# and a whole-file grep matched that prose. Fifth time in this suite.
code "$FMT" | grep -qE 'f3fix|mkfs\.exfat' \
  && bad "the exFAT rescue is being attempted — that needs parted and exfatprogs, neither of which ships" \
  || ok "no rescue path: a counterfeit card is refused, not repartitioned"
# 14 is not a number we picked: it is what the upstream helper returns for a card that failed the
# probe, and it is how the client knows to show its bad-card error rather than a generic one.
code "$FMT" | grep -q 'and a library on it would lose data" 14' \
  && ok "and it exits 14, the code the client maps to its bad-card error" \
  || bad "a failed card does not exit 14 — the UI would show a generic failure"
# stage= on stdout is what drives the format dialog's progress through Testing and Formatting.
for s in testing formatting; do
  code "$FMT" | grep -q "echo \"stage=$s\"" \
    && ok "emits stage=$s for the client's progress UI" \
    || bad "no stage=$s line — the dialog cannot show that phase"
done

# AND THAT "says so" HAS TO REACH SOMEWHERE. The automounter is a unit, so the journal collects its
# stderr; this script is exec'd by the client through pkexec, so its stderr is steamui's and lands
# nowhere. Measured on hardware after a successful format: not one line of it existed on the device.
# SYNCHRONOUS, LINE BY LINE — not upstream's `exec &> >(tee /dev/fd/8 | logger)`. That was tried
# and measured worse here: under pkexec it produced not one journal line for a whole format, and
# over ssh it delayed output past the process that wrote it. Nothing waits for that pipeline.
code "$FMT" | grep -q 'logger -t "\$PROG"' \
  && ok "each line reaches the journal as it is written" \
  || bad "log() writes to stderr only — through pkexec that output is lost, refusals included"
code "$FMT" | grep -q 'tee /dev/fd/8' \
  && bad "the async tee is back — it lost an entire format's output under pkexec" \
  || ok "and the async tee is not used"
code "$FMT" | grep -q 'log "mkfs: \$l"' \
  && ok "mkfs output is captured and logged the same way, rather than discarded" \
  || bad "mkfs output goes nowhere"
# die() logs $1, not $*: called as `die "reason" 13`, $* put the exit code inside every refusal the
# user could read — "must run as root (…) 13".
code "$FMT" | grep -q 'die()  { log "\$1"' \
  && ok "and die logs its message, not its message plus the exit code" \
  || bad "die logs \$* — the exit code leaks into the message"

# =================================================================================================
CASE="the-rest-of-the-upstream-mount-path"
# Ported after a line-by-line audit against jupiter-hw-support, each with its own reason.
code "$FMT" | grep -q 'root_owner=\$OWNER' \
  && ok "ownership is set by mkfs, not by mounting the new filesystem to chown it" \
  || bad "ownership still needs a mount/chown/umount cycle, which emits its own udev events"
code "$FMT" | grep -qE 'mount "\$PART" "\$tmp"' \
  && bad "the mount/chown/umount cycle is back" \
  || ok "and that cycle is gone"
code "$EVT" | grep -q 'udevadm settle' \
  && ok "udev is allowed to settle before udisks is asked anything" \
  || bad "no settle — udisks may not know about the device yet"
code "$EVT" | grep -q 'TimeMediaDetected' \
  && ok "an add event for media that was not just inserted is skipped (repartition, not insert)" \
  || bad "no recency check — repartitioning re-triggers a mount"
code "$EVT" | grep -q 'systemctl -q check multi-user.target' \
  && ok "and that check is skipped during boot, where the events legitimately arrive late" \
  || bad "the recency check would refuse cold-boot cards"
# THE SPLIT UPSTREAM GETS FOR FREE. Their entry point asks "does this udev event deserve a mount"
# (lock, settle, recency); their mounter asks none of it, and their formatter calls the mounter. One
# file playing both parts must tell them apart, or the recency check refuses the formatter's own
# post-format mount — a card in the slot for minutes was not "inserted recently" — and an unmounted
# card is what makes the client say the drive still needs formatting. HW-caught 2026-09-03.
# THE SPLIT ITSELF IS THE ASSERTION. The mounter must contain no event-filtering code, because the
# formatter calls it directly and none of those questions apply to a filesystem just created on
# purpose. Held in one file behind a guard, forgetting the guard broke this feature twice in an
# afternoon; held in two files there is nothing to forget.
for c in 'udevadm settle' 'TimeMediaDetected' 'storage_lock'; do
  code "$AUTO" | grep -q "$c" \
    && bad "the mounter still contains '$c' — it will misapply it to the formatter's own call" \
    || ok "the mounter contains no '$c'"
done
code "$EVT" | grep -q 'exec "\$MOUNTER" add' \
  && ok "and the entry point hands off to the mounter by exec, keeping the lock held" \
  || bad "the entry point does not exec the mounter"
code "$AUTO" | grep -q 'fsck.ext4 -y' \
  && ok "the filesystem is repaired before it is mounted" \
  || bad "no fsck — a dirty card mounts unrepaired"
code "$AUTO" | grep -q 'OPTS="\$OPTS,ro"' \
  && ok "and one that cannot be repaired mounts read-only" \
  || bad "an unrepairable card would still mount read-write"
code "$AUTO" | grep -q 'options s "\$OPTS"' \
  && ok "the options reach udisks" || bad "OPTS is computed and then not passed"
code "$AUTO" | grep -q 'setpriv --clear-groups' \
  && ok "writability is tested as deck, not inferred from mode bits" \
  || bad "nothing checks that deck can write the mountpoint"
# NOT PORTED, and deliberately: the steam:// URL that reports a failed fsck to the client.
code "$AUTO" | grep -q 'devicemountresult' \
  && bad "an unmeasured steam:// call was added — the last one created libraries on every card" \
  || ok "no devicemountresult URL: its effect on this client has never been observed"

# =================================================================================================
printf '\ntest-storage.sh: %d passed, %d failed\n' "$PASS" "$FAIL"
[ "$FAIL" -eq 0 ]
