# novadeck slot-write primitives — Phase 2 of .claude/plans/internal-install.plan.md.
#
# SOURCED, never executed (hence mode 0644, like gamescope-display.sh and power-ops.sh).
#
# WHY THIS FILE EXISTS: everything a RAUC bundle does NOT carry has to be written twice -- once by
# the OTA path (fs-overlay/usr/lib/rauc/post-install.sh) and once by the internal installer, which
# writes the same artifacts onto a disk that has no novadeck on it yet. Two copies of that logic
# would drift, and the direction they drift in is "the installed system boots, the updated one does
# not" or the reverse -- discoverable only on hardware, on a device with no serial console. So the
# shared half lives here and post-install.sh sources it.
#
# The functions take explicit arguments and touch nothing implicitly: the OTA path addresses a
# running system's /esp and /efi, the installer addresses mountpoints under /run on a foreign disk,
# and a primitive that reached for a global would be right for exactly one of them.

# die() is the caller's if it has one -- post-install.sh's prefixes [post-install.sh] and exits 1,
# and its offline suite asserts that shape. Only define a fallback when sourced by something that
# has not got one.
if ! declare -F die >/dev/null 2>&1; then
  die() { printf '[lib-slotwrite] ERROR: %s\n' "$1" >&2; exit 1; }
fi

# --- parts.env (phase 1b) -----------------------------------------------------------------------
# The map stage 2 reads before it can address anything: where our eight partitions ARE on this
# medium. On a card they are 1..8; on an internal install genpart.sh --append discovers them from
# the OEM's GPT and they are neither row order nor contiguous (an ESP at p3 while sitting physically
# last is a real observed case). This is the one file that tells stage 2 which is which.
#
# WRITTEN BY HAND rather than with grub-editenv, and that is deliberate. Unlike every other artifact
# in the install, parts.env's CONTENTS ARE PER-DISK -- they come from what --append just laid down on
# this specific device -- so the trick used for the ESP's grubenv (build a pristine block at image
# build time, have the device cp it) does not transfer. It has to be generated on the device, and
# grub-editenv is not on the shipped image: no grub in customize-base.sh's PKGS, no
# /usr/bin/grub-editenv in the built base (confirmed 2026-08-06). Adding it to the INSTALLER's
# package list would be free, but the format is trivial and fixed, and the installer already has to
# add gptfdisk and dosfstools -- this is one fewer.
#
# The format, verified against grub-editenv's own output rather than from the docs:
#
#   "# GRUB Environment Block\n"   the signature: 24 characters + \n. envblk.c memcmp's it, so it
#                                  is the one load-bearing part and must match byte for byte.
#   "# WARNING: ...\n"             what grub-editenv writes. A comment, so inert to the reader --
#                                  reproduced anyway so a card's parts.env and an install's are the
#                                  same shape, and one file can be diffed against the other.
#   "key=value\n"                  one per line. grub_envblk_iterate starts after the signature and
#                                  skips any line beginning with '#'.
#   "####..."                      '#' padding, no trailing newline, out to EXACTLY 1024 bytes.
GRUB_ENVBLK_SIGNATURE='# GRUB Environment Block'
GRUB_ENVBLK_WARNING='# WARNING: Do not edit this file by tools other than grub-editenv!!!'
GRUB_ENVBLK_SIZE=1024

# Pure: emits the block on stdout, touches nothing. Everything that can be asserted about the
# format is asserted about THIS, which is why it is separate from the function that writes a file.
parts_env_block() {  # <key=value>...
  local body pad
  body="$GRUB_ENVBLK_SIGNATURE"$'\n'"$GRUB_ENVBLK_WARNING"$'\n'
  local kv
  for kv in "$@"; do
    case "$kv" in
      *=*) ;;
      *) die "parts.env entry '$kv' is not key=value" ;;
    esac
    body+="$kv"$'\n'
  done

  # THE ASSERTION THAT MATTERS. grub_envblk_open only requires the SIGNATURE to fit, so a block of
  # the wrong length still reads back correctly with grub-editenv and would differ from what
  # make-sdcard.sh writes on a card. Nothing downstream would complain; the file would simply not be
  # the same object the card carries. Check the length here, where it is cheap.
  pad=$(( GRUB_ENVBLK_SIZE - ${#body} ))
  [ "$pad" -ge 0 ] \
    || die "parts.env content is ${#body} bytes, over the $GRUB_ENVBLK_SIZE-byte block"

  printf '%s' "$body"
  # No trailing newline after the padding -- grub-editenv's block ends on '#'.
  [ "$pad" -gt 0 ] && printf '%*s' "$pad" '' | tr ' ' '#'
  return 0
}

# Writes the block to the slot's efi partition. <mnt> is where that partition is mounted -- /efi on
# a running system, a /run mountpoint on the disk being installed.
write_parts_env() {  # <mnt> <key=value>...
  local mnt="$1"; shift
  [ -d "$mnt" ] || die "no efi mountpoint at $mnt for parts.env"
  mkdir -p "$mnt/EFI/steamos" || die "cannot create $mnt/EFI/steamos"
  parts_env_block "$@" >"$mnt/EFI/steamos/parts.env" \
    || die "cannot write $mnt/EFI/steamos/parts.env"
}

# genpart.sh --append prints `<gpt-name>=<index>`; stage 2 reads `nd_<role>`. This is the only place
# that knows the correspondence, so a rename in partition-table.txt breaks HERE, loudly, rather than
# producing a parts.env that is well-formed and names nothing.
parts_env_from_genpart_map() {  # reads the map on stdin, emits key=value on stdout
  local line name idx key
  while IFS='=' read -r name idx; do
    [ -n "$name" ] || continue
    case "$name" in
      NOVADECK-ESP)    key=nd_esp ;;
      novadeck-efi-A)  key=nd_efi_a ;;
      novadeck-efi-B)  key=nd_efi_b ;;
      novadeck-root-A) key=nd_root_a ;;
      novadeck-root-B) key=nd_root_b ;;
      novadeck-var-A)  key=nd_var_a ;;
      novadeck-var-B)  key=nd_var_b ;;
      novadeck-home)   key=nd_home ;;
      *) die "genpart map names '$name', which parts.env has no key for" ;;
    esac
    case "$idx" in
      ''|*[!0-9]*) die "genpart map gives '$name' a non-numeric index '$idx'" ;;
    esac
    printf '%s=%s\n' "$key" "$idx"
  done
}
