#!/usr/bin/env bash
# novadeck lock materializer — turn images/manifest.lock into a verified install list
# (Phase 4a step 2). Host-side: no container, no emulation, everything it needs is a file.
#
#   images/fetchlock.sh <install-list-out>
#
# Writes one CONTAINER-visible package path per line to <install-list-out>, which
# images/customize-base.sh stages into the bootstrap container and feeds to a single
# `pacman -U`. That replaces `pacman -Sy <names>`: dependency resolution stops happening
# implicitly against a live repo database at build time. The lock IS the resolved closure,
# and it is only ever regenerated by an explicit `make relock`.
#
# WHAT THIS VERIFIES, AND WHY IT IS THE STRONGER CHECK: every fetched file is matched against the
# sha256 committed in the lock before it is allowed into the install list. The snapshot repo
# is served SigLevel = Optional and the cache carries no detached .sig files, so pacman's own
# signature check is a no-op here — the reviewed hash in a committed artifact is what actually
# pins these bytes. A same-version upstream rebuild fails here rather than shipping silently.
#
# THE `novadeck` ROWS ARE CHECKED DIFFERENTLY, and the difference is deliberate — see below.
#
# Three of the lock's four provenance classes are installable and handled here:
#
#   snapshot  from the pinned repo revision (snapshot.pin) via work/pacman-cache, which is
#             bind-mounted into the container at /var/cache/pacman/pkg. Fetched on a cache
#             miss, verified either way.
#   stripped  fetched and verified EXACTLY like a snapshot row — the class marks disposition,
#             not provenance. These four (pacman, pacman-mirrorlist, gnupg, archlinux-keyring)
#             arrive as `base` metapackage dependencies, so the bootstrap cannot skip them;
#             images/seal-rootfs.sh deletes them from the release tree afterwards (Phase 4a
#             step 3). Before Phase 4c they came in with the base image and there was no file
#             to fetch, which is why this class used to be skipped here.
#   novadeck  built from source by packages/build-overlay.sh into work/repo/aarch64, mounted
#             at /novarepo. NEVER fetched — there is nowhere to fetch it from. The lock's hash
#             for these rows is NOT the artifact's sha256: it is packages/inputhash.sh over the
#             package's committed sources (source.pin + patches + local PKGBUILD), so what is
#             checked here is "these artifacts were built from the sources the lock names",
#             re-derived from the repo rather than read off a stamp.
#
#             WHY, since a byte check is obviously stronger: our overlay builds are not
#             bit-reproducible. Rebuilding from IDENTICAL inputs moved all 10 artifact hashes, so
#             the old check only ever passed on the machine that last ran `make relock` — it
#             could say "you rebuilt" but never "the inputs changed". `make distclean && make
#             sdcard` could not succeed on its own, and a clean CI runner (no work/, so it
#             rebuilds the overlay) failed every single run. The claim is weaker about the
#             artifact — anyone who can write work/repo can substitute one — and stronger about
#             provenance, which is the half that has to survive crossing a machine. The proper
#             fix is to publish overlay builds as sha-pinned `prebuilt` rows from a package
#             pipeline; that restores the byte check and is tracked in TODO.md.
#
# The fourth is not an install: `prebuilt` rows are tarballs/blobs placed by customize-base.sh
# from their own sha256-pinned packages/*/prebuilt.pin.
#
# There is no `base` class any more. It named the 116 packages that shipped inside the
# digest-pinned container image the root used to be exported from — no file, so nothing for
# this script to verify. The root is bootstrapped now (Phase 4c), so every row is installable
# and this script covers the whole package set rather than 282 of 398 rows.
#
# WHY THE REPO NAME IS GUESSED rather than recorded in the lock: pacman's LOCAL database has no
# repo field, so genmanifest.sh — which reads that database — has no repo to record. Only core
# and extra are configured (both Include the one pinned mirrorlist), so a cache miss tries them
# in turn. It costs one extra request on a miss and cannot silently pick the wrong file: the
# sha256 still has to match.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LOCK="$ROOT/images/manifest.lock"
CACHE="$ROOT/work/pacman-cache"
OVERLAY_REPO="$ROOT/work/repo/aarch64"
SNAPFILE="$ROOT/snapshot.pin"

OUT="${1:?usage: images/fetchlock.sh <install-list-out>}"

# Repos configured in the base's pacman.conf, in that order. See the header note on guessing.
REPOS=(core extra)
# The repo path segment is pacman's $arch, NOT the package's. An `any` package still lives under
# aarch64/ while its FILENAME ends in -any.pkg.tar.zst — conflating the two 404s on 18 rows.
REPO_ARCH=aarch64

[ -f "$LOCK" ] || { echo "no manifest: $LOCK (run \`make relock\`)" >&2; exit 1; }
[ -f "$SNAPFILE" ] || { echo "no snapshot pin: $SNAPFILE" >&2; exit 1; }
SNAPSHOT="$(grep -vE '^[[:space:]]*(#|$)' "$SNAPFILE" | tail -1)"
mkdir -p "$CACHE"

# Overlay artifact -> "<input hash>\t<package dir>" of the source pin that produced it. The
# mapping comes from the per-package artifact lists packages/build-overlay.sh writes, because one
# PKGBUILD can emit several packages (mesa emits five, of which three are installed) and only the
# builder knows which. The HASH is re-derived from the repo's own committed files, never read from
# a stamp: a stamp is the builder's claim about itself, and the point of the check is to compare
# the lock against the sources a reviewer can actually see.
declare -A PINHASH
for pin in "$ROOT"/packages/*/source.pin; do
  [ -e "$pin" ] || continue
  pdir="$(dirname "$pin")"
  pname="$(sed -n 's/^name:[[:space:]]*//p' "$pin" | head -1)"
  [ -f "$OVERLAY_REPO/.stamps/$pname.files" ] || continue
  h="$("$ROOT/packages/inputhash.sh" "$pdir")"
  while read -r f; do
    [ -n "$f" ] && PINHASH["$f"]="$h	${pdir#"$ROOT"/}"
  done < "$OVERLAY_REPO/.stamps/$pname.files"
done

# Fetch one package into the cache and verify it, or fail. Tries each repo in turn; a 404 is a
# normal miss (the package is in the other repo), anything else surfaces on the last attempt.
fetch_pkg() {
  local file="$1" sha="$2" dest="$CACHE/$1" repo url
  for repo in "${REPOS[@]}"; do
    url="$SNAPSHOT/$repo/os/$REPO_ARCH/$file"
    curl -fsSL "$url" -o "$dest.part" 2>/dev/null || continue
    if echo "$sha  $dest.part" | sha256sum -c --status -; then
      mv -f "$dest.part" "$dest"
      echo "[novadeck] lock: fetched $file ($repo)" >&2
      return 0
    fi
    rm -f "$dest.part"
    echo "$file: sha256 mismatch against the lock at $url" >&2
    echo "  the pinned revision republished this version — bump snapshot.pin or \`make relock\`" >&2
    return 1
  done
  rm -f "$dest.part"
  echo "$file: not found in ${REPOS[*]} under $SNAPSHOT" >&2
  return 1
}

rows=0 fetched=0 cached=0 overlay=0
list=""
while read -r name ver arch src sha; do
  case "$name" in ''|'#'*) continue ;; esac
  file="$name-$ver-$arch.pkg.tar.zst"

  case "$src" in
    snapshot|stripped)
      if [ -f "$CACHE/$file" ] && echo "$sha  $CACHE/$file" | sha256sum -c --status -; then
        cached=$((cached + 1))
      else
        # A present-but-mismatched file is a stale cache entry (a truncated download, or an
        # older artifact under the same name) — re-fetch over it rather than trusting it.
        rm -f "$CACHE/$file"
        fetch_pkg "$file" "$sha"
        fetched=$((fetched + 1))
      fi
      list+="/var/cache/pacman/pkg/$file"$'\n'
      ;;
    novadeck)
      # Not fetchable: this is our own build artifact. The file must be there, and the sources it
      # was built from must be the ones the lock names — a plain rebuild is fine and changes
      # nothing here, an edited patch or bumped pin is what has to move the lock.
      if [ ! -f "$OVERLAY_REPO/$file" ]; then
        echo "$file: missing from the overlay repo (${OVERLAY_REPO#"$ROOT"/})" >&2
        echo "  build it (\`make overlay\`) or \`make relock\` if the version moved" >&2
        exit 1
      fi
      entry="${PINHASH["$file"]:-}"
      if [ -z "$entry" ]; then
        echo "$file: in the overlay repo, but no packages/*/source.pin claims it" >&2
        echo "  ${OVERLAY_REPO#"$ROOT"/}/.stamps is stale or absent -> rebuild: make overlay" >&2
        exit 1
      fi
      if [ "${entry%%	*}" != "$sha" ]; then
        echo "$file: built from different sources than images/manifest.lock records" >&2
        echo "    lock: $sha" >&2
        echo "    tree: ${entry%%	*}   (${entry#*	}: source.pin + patches + PKGBUILD)" >&2
        echo "  review that source change and \`make relock\` to adopt it" >&2
        exit 1
      fi
      overlay=$((overlay + 1))
      list+="/novarepo/$file"$'\n'
      ;;
    prebuilt) continue ;;   # not a pacman package — see the header
    *) echo "$LOCK: unknown source class '$src' for $name" >&2; exit 1 ;;
  esac
  rows=$((rows + 1))
done < "$LOCK"

[ "$rows" -gt 0 ] || { echo "$LOCK: no installable rows — refusing an empty install" >&2; exit 1; }

# Write the list only once every row verified, so a failure can never leave a partial list
# behind for the container to install from.
printf '%s' "$list" >"$OUT"
echo "[novadeck] lock: $rows packages verified ($cached cached, $fetched fetched, $overlay overlay)" >&2
