#!/usr/bin/env bash
# novadeck lock materializer — turn images/manifest.lock into a verified install list
# (Phase 4a step 2). Host-side: no container, no emulation, everything it needs is a file.
#
#   images/fetchlock.sh <install-list-out>
#
# Writes one CONTAINER-visible package path per line to <install-list-out>, which
# images/customize-base.sh stages into the customization container and feeds to a single
# `pacman -U`. That replaces `pacman -Sy <names>`: dependency resolution stops happening
# implicitly against a live repo database at build time. The lock IS the resolved closure,
# and it is only ever regenerated by an explicit `make relock`.
#
# WHAT THIS VERIFIES, AND WHY IT IS THE STRONGER CHECK: every file is matched against the
# sha256 committed in the lock before it is allowed into the install list. The snapshot repo
# is served SigLevel = Optional and the cache carries no detached .sig files, so pacman's own
# signature check is a no-op here — the reviewed hash in a committed artifact is what actually
# pins these bytes. A same-version upstream rebuild fails here rather than shipping silently.
#
# Two of the lock's four provenance classes are installable and handled here:
#
#   snapshot  from the pinned repo revision (snapshot.pin) via work/pacman-cache, which is
#             bind-mounted into the container at /var/cache/pacman/pkg. Fetched on a cache
#             miss, verified either way.
#   novadeck  built from source by packages/build-overlay.sh into work/repo/aarch64, mounted
#             at /novarepo. NEVER fetched — a missing or mismatched file means the overlay was
#             rebuilt and the lock is stale, which is a `make relock`, not a download.
#
# The other three are not installs: `base` rows already ship inside the digest-pinned base image
# (no package file exists to install), `prebuilt` rows are tarballs/blobs placed by
# customize-base.sh from their own sha256-pinned packages/*/prebuilt.pin, and `stripped` rows are
# base rows that images/seal-rootfs.sh then deletes from the release image (Phase 4a step 3) —
# genmanifest.sh refuses to mark anything installable `stripped` precisely so this stays true.
#
# WHY THE REPO NAME IS GUESSED rather than recorded in the lock: pacman's LOCAL database has no
# repo field, so genmanifest.sh — which reads that database — has no repo to record. Only core
# and extra are configured (both Include the one pinned mirrorlist), so a cache miss tries them
# in turn. It costs one extra request on a miss and cannot silently pick the wrong file: the
# sha256 still has to match.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LOCK="$ROOT/images/manifest.lock"
CACHE="$ROOT/work/pacman-cache"
OVERLAY_REPO="$ROOT/work/repo/aarch64"
SNAPFILE="$ROOT/snapshot.pin"

OUT="${1:?usage: images/fetchlock.sh <install-list-out>}"

# Repos configured in the base's pacman.conf, in that order. See the header note on guessing.
REPOS=(core extra)
# The repo path segment is pacman's $arch, NOT the package's. An `any` package still lives under
# aarch64/ while its FILENAME ends in -any.pkg.tar.zst — conflating the two 404s on 18 rows.
REPO_ARCH=aarch64

[ -f "$LOCK" ] || { echo "no manifest: $LOCK (run \`make relock\`)" >&2; exit 1; }
[ -f "$SNAPFILE" ] || { echo "no snapshot pin: $SNAPFILE" >&2; exit 1; }
SNAPSHOT="$(grep -vE '^[[:space:]]*(#|$)' "$SNAPFILE" | tail -1)"
mkdir -p "$CACHE"

# Fetch one package into the cache and verify it, or fail. Tries each repo in turn; a 404 is a
# normal miss (the package is in the other repo), anything else surfaces on the last attempt.
fetch_pkg() {
  local file="$1" sha="$2" dest="$CACHE/$1" repo url
  for repo in "${REPOS[@]}"; do
    url="$SNAPSHOT/$repo/os/$REPO_ARCH/$file"
    curl -fsSL "$url" -o "$dest.part" 2>/dev/null || continue
    if echo "$sha  $dest.part" | sha256sum -c --status -; then
      mv -f "$dest.part" "$dest"
      echo "[novadeck] lock: fetched $file ($repo)" >&2
      return 0
    fi
    rm -f "$dest.part"
    echo "$file: sha256 mismatch against the lock at $url" >&2
    echo "  the pinned revision republished this version — bump snapshot.pin or \`make relock\`" >&2
    return 1
  done
  rm -f "$dest.part"
  echo "$file: not found in ${REPOS[*]} under $SNAPSHOT" >&2
  return 1
}

rows=0 fetched=0 cached=0 overlay=0
list=""
while read -r name ver arch src sha; do
  case "$name" in ''|'#'*) continue ;; esac
  file="$name-$ver-$arch.pkg.tar.zst"

  case "$src" in
    snapshot)
      if [ -f "$CACHE/$file" ] && echo "$sha  $CACHE/$file" | sha256sum -c --status -; then
        cached=$((cached + 1))
      else
        # A present-but-mismatched file is a stale cache entry (a truncated download, or an
        # older artifact under the same name) — re-fetch over it rather than trusting it.
        rm -f "$CACHE/$file"
        fetch_pkg "$file" "$sha"
        fetched=$((fetched + 1))
      fi
      list+="/var/cache/pacman/pkg/$file"$'\n'
      ;;
    novadeck)
      # Not fetchable: this is our own build artifact. A mismatch means the overlay was rebuilt
      # since the lock was written, so the lock — not the tree — is what has to move.
      if [ ! -f "$OVERLAY_REPO/$file" ]; then
        echo "$file: missing from the overlay repo (${OVERLAY_REPO#"$ROOT"/})" >&2
        echo "  build it (\`make overlay\`) or \`make relock\` if the version moved" >&2
        exit 1
      fi
      if ! echo "$sha  $OVERLAY_REPO/$file" | sha256sum -c --status -; then
        echo "$file: sha256 differs from the lock — the overlay was rebuilt" >&2
        echo "  review and \`make relock\` to adopt the new build" >&2
        exit 1
      fi
      overlay=$((overlay + 1))
      list+="/novarepo/$file"$'\n'
      ;;
    base|prebuilt|stripped) continue ;;   # not installs — see the header
    *) echo "$LOCK: unknown source class '$src' for $name" >&2; exit 1 ;;
  esac
  rows=$((rows + 1))
done < "$LOCK"

[ "$rows" -gt 0 ] || { echo "$LOCK: no installable rows — refusing an empty install" >&2; exit 1; }

# Write the list only once every row verified, so a failure can never leave a partial list
# behind for the container to install from.
printf '%s' "$list" >"$OUT"
echo "[novadeck] lock: $rows packages verified ($cached cached, $fetched fetched, $overlay overlay)" >&2
