#!/usr/bin/env bash
# novadeck package manifest generator -> images/manifest.lock  (Phase 4a step 1).
#
# Records EXACTLY what the customized base contains, so a base rebuild is a reviewable
# diff instead of a 395-package black box. Runs on the HOST against the already-exported
# base tree — no container, no emulation: everything it needs is a file.
#
#   images/genmanifest.sh [base-rootfs-dir]     (default: work/base)
#
# WHY sha256 and not just name-version: our mirror pin used to be the UNSUFFIXED snapshot
# path, which is an alias tracking the newest revision (see snapshot.pin). Revisions can
# republish the same package version built from the same source at a different pkgrel-less
# artifact, so equal versions do NOT prove equal package files. The hash is the only field
# that actually detects that.
#
# Four provenance classes, because they are pinned by genuinely different mechanisms and
# conflating them would overstate what we verify:
#
#   snapshot  installed from the pinned repo revision; hash = the .pkg.tar.zst we installed
#   novadeck  built from source by packages/build-overlay.sh; hash = our own build artifact
#   base      arrived INSIDE the pinned base image and was never downloaded, so there is no
#             package file to hash. Pinned by base.digest (itself a sha256) — recorded with
#             a '-' hash rather than silently omitted, because they are on the image.
#   prebuilt  not pacman packages at all: the tarballs/blobs in packages/*/prebuilt.pin,
#             already sha256-pinned there. Carried so the lock covers the whole image.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BASE="${1:-${BASE_ROOTFS:-$ROOT/work/base}}"
LOCK="$ROOT/images/manifest.lock"
CACHE="$ROOT/work/pacman-cache"
OVERLAY_REPO="$ROOT/work/repo/aarch64"
LOCALDB="$BASE/var/lib/pacman/local"

[ -d "$LOCALDB" ] || { echo "no pacman local db under $BASE (customize the base first)" >&2; exit 1; }

# Index the two package directories ONCE by exact filename. Deliberately not a per-package
# glob: the cache accumulates stale versions (e.g. mesa 26.1.4 alongside 26.1.5), so a glob
# would happily match the wrong artifact. Exact name-version-arch or nothing.
declare -A PKGFILE
index_dir() {
  local dir="$1" src="$2" f
  [ -d "$dir" ] || return 0
  for f in "$dir"/*.pkg.tar.zst; do
    [ -e "$f" ] || continue
    PKGFILE["$(basename "$f")"]="$src	$f"
  done
}
# Cache first, overlay second, so the overlay OVERWRITES on collision — matching pacman.conf
# repo ORDER, where the overlay repo sits ahead of the snapshot repos and order beats version.
index_dir "$CACHE" snapshot
index_dir "$OVERLAY_REPO" novadeck

# One row per installed package, read straight out of the local db's desc files. Field order
# in desc is not guaranteed, so each is matched by its own %KEY% rather than by position.
desc_field() { sed -n "/^%$2%\$/{n;p;q}" "$1"; }

rows=""
missing=0
for d in "$LOCALDB"/*/; do
  desc="$d/desc"
  [ -f "$desc" ] || continue
  name="$(desc_field "$desc" NAME)"
  ver="$(desc_field "$desc" VERSION)"
  arch="$(desc_field "$desc" ARCH)"
  [ -n "$name" ] && [ -n "$ver" ] || { echo "malformed desc: $desc" >&2; exit 1; }
  arch="${arch:-any}"

  entry="${PKGFILE["$name-$ver-$arch.pkg.tar.zst"]:-}"
  if [ -n "$entry" ]; then
    src="${entry%%	*}"; file="${entry#*	}"
    sha="$(sha256sum "$file" | cut -d' ' -f1)"
  else
    # Came with the base image: covered by base.digest, no artifact of ours to hash.
    src=base; sha='-'
    missing=$((missing + 1))
  fi
  rows+="$name $ver $arch $src $sha"$'\n'
done

# Prebuilt pins: name/version/sha256 are already declared and host-verified by
# customize-base.sh, so read them from the pin rather than re-deriving.
pin_field() { sed -n "s/^$2:[[:space:]]*//p" "$1" | head -1; }
for pin in "$ROOT"/packages/*/prebuilt.pin; do
  [ -e "$pin" ] || continue
  p_name="$(pin_field "$pin" name)"
  p_ver="$(pin_field "$pin" version)"
  p_sha="$(pin_field "$pin" sha256)"
  [ -n "$p_name" ] && [ -n "$p_sha" ] || { echo "$pin: missing name/sha256" >&2; exit 1; }
  rows+="$p_name ${p_ver:--} - prebuilt $p_sha"$'\n'
done

snapshot="$(grep -vE '^[[:space:]]*(#|$)' "$ROOT/snapshot.pin" 2>/dev/null | tail -1 || true)"
basedigest="$(grep -vE '^[[:space:]]*(#|$)' "$ROOT/base.digest" | tail -1)"

{
  echo "# novadeck package manifest — GENERATED by images/genmanifest.sh, do not hand-edit."
  echo "# Regenerate with \`make relock\` after any deliberate package change; review the diff."
  echo "#"
  echo "# base image:    $basedigest"
  echo "# repo snapshot: ${snapshot:-<unpinned>}"
  echo "#"
  echo "# name version arch source sha256   (source: snapshot|novadeck|base|prebuilt)"
  echo "# 'base' rows carry no hash: they ship inside the base image, pinned by its digest."
  printf '%s' "$rows" | LC_ALL=C sort
} >"$LOCK"

echo "[novadeck] manifest -> ${LOCK#"$ROOT"/}" >&2
awk '!/^#/ {n[$4]++; t++} END {for (s in n) printf "  %-9s %4d\n", s, n[s]; printf "  %-9s %4d\n", "TOTAL", t}' "$LOCK" >&2
