#!/usr/bin/env bash
# Phase 3 hardware validation of install/select-target.sh — READ ONLY, on a real device.
#
#   install/hw-select-target.sh root@<device> > docs/internal-select-target.md
#
# The offline suite (install/test-select-target.sh) drives the same script against GPTs rebuilt
# from the Phase 0 captures, and it is green — but on IMAGE FILES, where sgdisk always reports
# 512-byte sectors because it only asks the kernel for the logical size on a block device. Real
# UFS LUNs report 4096. So the whole sector-size path, the LUN enumeration, and rules 1/2 (the
# running disk is never a candidate) have no coverage until this runs. That is what this is for,
# and it is the only thing Phase 3 still owed after the suites went green.
#
# NOTHING HERE WRITES TO THE DEVICE outside /run/novadeck/probe, which is tmpfs and gone at the
# next boot. select-target.sh is pure by construction; this wrapper adds no writes of its own,
# which is why it is safe to run against any board at any time, including one carrying an install
# somebody cares about.
#
# sgdisk is staged rather than assumed: gptfdisk is NOT in the shipped image, it is on the
# installer image's package list only (plan Phase 6). Its DT_NEEDED closure — libuuid, libpopt,
# libstdc++, libgcc_s — is satisfied by packages the image already carries (util-linux-libs, popt,
# gcc-libs are all rows in images/manifest.lock), so the bare binary is enough and no libraries
# travel with it. Verify that again after a snapshot bump; a new dependency would surface here as
# a loader error on the device rather than as a failure to fetch.
set -euo pipefail

host="${1:-}"
[ -n "$host" ] || { echo "usage: ${0##*/} <user@host>   (e.g. root@192.168.1.166)" >&2; exit 2; }

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cache="$ROOT/work/hw-sgdisk"

# The package, pinned by sha256 the same way every other external artifact in this tree is
# (packages/*/prebuilt.pin, the kernel tarball). The repo it comes from is images/manifest.lock's
# snapshot, read from the file rather than duplicated, so a `make relock` cannot leave this
# fetching from a snapshot the image no longer uses. To bump: change VERSION + SHA256 together
# after a relock, and re-check the NEEDED closure noted above.
GPTFDISK_VERSION="1.0.10-1"
GPTFDISK_SHA256="6512d21ab6b504d36f45bec0c4b0f692179ff4a916707e0f050a1c56f4181704"
pkg="gptfdisk-${GPTFDISK_VERSION}-aarch64.pkg.tar.zst"

snapshot="$(sed -n 's|^# repo snapshot: *||p' "$ROOT/images/manifest.lock" | head -1)"
[ -n "$snapshot" ] || { echo "no '# repo snapshot:' line in images/manifest.lock" >&2; exit 1; }

# --- stage 1: the binary, fetched once and cached under work/ (gitignored) -------------------
sgdisk="$cache/usr/bin/sgdisk"
if [ ! -x "$sgdisk" ]; then
  mkdir -p "$cache"
  echo "[novadeck] fetching $pkg from $snapshot" >&2
  curl -fsSL -o "$cache/$pkg" "$snapshot/extra/os/aarch64/$pkg"
  got="$(sha256sum "$cache/$pkg" | cut -d' ' -f1)"
  [ "$got" = "$GPTFDISK_SHA256" ] || {
    rm -f "$cache/$pkg"
    echo "sha256 mismatch for $pkg: got $got, pinned $GPTFDISK_SHA256" >&2; exit 1; }
  tar -I zstd -C "$cache" -xf "$cache/$pkg" usr/bin/sgdisk
  chmod +x "$sgdisk"
fi

# --- stage 2: onto the device ----------------------------------------------------------------
# The dev card's throwaway key (dev.env mints it). IdentitiesOnly, so an agent holding many keys
# cannot spend the server's auth attempts before this one is offered.
key="$ROOT/work/dev-ssh/id_ed25519"
SSHOPTS=(-o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new -o ConnectTimeout=10)
[ -f "$key" ] && SSHOPTS+=(-i "$key")

ssh "${SSHOPTS[@]}" "$host" 'mkdir -p /run/novadeck/probe'
scp "${SSHOPTS[@]}" -q "$sgdisk" "$ROOT/install/select-target.sh" "$host:/run/novadeck/probe/"
ssh "${SSHOPTS[@]}" "$host" 'chmod +x /run/novadeck/probe/sgdisk /run/novadeck/probe/select-target.sh'

# --- stage 3: the run ------------------------------------------------------------------------
# Markdown on stdout, per-board sections that concatenate, exactly like probe-internal.sh's
# capture — for the same reason: boards differ, so the document is a set of sections and never a
# single canonical table.
ssh "${SSHOPTS[@]}" "$host" 'bash -s' <<'REMOTE'
set -u
export PATH=/run/novadeck/probe:$PATH
ST=/run/novadeck/probe/select-target.sh

model="$( { tr -d '\0' < /sys/firmware/devicetree/base/model; } 2>/dev/null )"
echo "# select-target hardware run — ${model:-unknown board}"
echo
echo "Generated by \`install/hw-select-target.sh\` — read-only Phase 3 validation."
echo
echo '| | |'
echo '|---|---|'
echo "| Ran | $(date -u '+%Y-%m-%dT%H:%M:%SZ') |"
echo "| Board | \`${model:-?}\` |"
echo "| Kernel | \`$(uname -r)\` |"
echo "| sgdisk | \`$(sgdisk --version 2>&1 | head -1)\` |"
for k in NOVADECK_VARIANT NOVADECK_MODE NOVADECK_VERSION NOVADECK_BUILD NOVADECK_GIT; do
  v="$(sed -n "s/^$k=//p" /etc/novadeck-release 2>/dev/null | head -1 | tr -d '"')"
  [ -n "$v" ] && echo "| $k | \`$v\` |"
done
root_src="$(findmnt -no SOURCE / 2>/dev/null | sed 's/\[.*//')"
boot_disk="$(lsblk -no PKNAME "$root_src" 2>/dev/null | head -1 | awk '{print $1}')"
echo "| Running root | \`${root_src:-?}\` |"
echo "| Boot medium — never a target | \`${boot_disk:-?}\` |"
echo

# The fact no image fixture can produce: sgdisk asks the KERNEL for the logical size, and only on
# a block device. Every offline case runs at 512 whatever the captured board reported.
echo '## Logical / physical sector size per disk'
echo
echo '| Disk | logical | physical | size |'
echo '|---|---|---|---|'
for d in /sys/block/*; do
  n="$(basename "$d")"
  case "$n" in loop*|ram*|zram*|dm-*) continue ;; esac
  printf '| `%s` | %s | %s | %s |\n' "$n" \
    "$(cat "$d/queue/logical_block_size" 2>/dev/null || echo '?')" \
    "$(cat "$d/queue/physical_block_size" 2>/dev/null || echo '?')" \
    "$(lsblk -dno SIZE "/dev/$n" 2>/dev/null | tr -d ' ' || echo '?')"
done
echo

run() {
  echo '```'
  echo "\$ select-target.sh $*"
  out="$(bash "$ST" "$@" 2>&1)"; rc=$?
  printf '%s\n' "$out"
  echo "rc=$rc"
  echo '```'
  echo
}

echo '## The scan — no argument'
echo
echo 'Rules 1, 2 and 9 reach this path and no other: the explicit-target form below cannot pick a'
echo 'disk, so it cannot exercise "never pick when two are eligible" either.'
echo
run

echo '## Every disk, named explicitly'
echo
for n in $(lsblk -dno NAME | grep -Ev '^(loop|ram|zram|dm-)'); do
  echo "### \`/dev/$n\` — $(lsblk -dno SIZE "/dev/$n" | tr -d ' ')"
  echo
  echo "PARTLABELs: \`$(lsblk -no PARTLABEL "/dev/$n" 2>/dev/null | grep -v '^$' | tr '\n' ' ')\`"
  echo
  run "/dev/$n"
done
REMOTE

echo "[novadeck] staged files remain under /run/novadeck/probe (tmpfs); they vanish at reboot" >&2
