#!/usr/bin/env bash
# Phase 3 hardware validation of install/select-target.sh — READ ONLY, on a real device.
#
#   install/hw-select-target.sh root@<device> > docs/internal-select-target.md
#
# The offline suite (install/test-select-target.sh) drives the same script against GPTs rebuilt
# from the Phase 0 captures, and it is green — but on IMAGE FILES, where sgdisk always reports
# 512-byte sectors because it only asks the kernel for the logical size on a block device. Real
# UFS LUNs report 4096. So the whole sector-size path, the LUN enumeration, and rules 1/2 (the
# running disk is never a candidate) have no coverage until this runs. That is what this is for,
# and it is the only thing Phase 3 still owed after the suites went green.
#
# NOTHING HERE WRITES TO THE DEVICE outside /run/novadeck/probe, which is tmpfs and gone at the
# next boot. select-target.sh is pure by construction; this wrapper adds no writes of its own,
# which is why it is safe to run against any board at any time, including one carrying an install
# somebody cares about.
#
# TWO binaries are staged rather than assumed, because neither is in the shipped image — both are
# installer-image packages (plan Phase 6). The pins, the closures and the fetch live in
# install/lib-hwstage.sh, shared with install/hw-install.sh, which stages the same two plus the two
# more the destructive half needs. That file is where a snapshot bump is done.
#
# Staging mdir is not a convenience. Without it select-target.sh refuses outright (it fails closed
# since 2026-08-21), and before that change its absence made rule 3b answer "not bootable" for
# every ESP on the disk — which is how the FIT's ROCKNIX install went undetected. Rule 3b has no
# hardware coverage at all unless this binary travels with the script.
set -euo pipefail

host="${1:-}"
[ -n "$host" ] || { echo "usage: ${0##*/} <user@host>   (e.g. root@192.168.1.166)" >&2; exit 2; }

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# shellcheck source=lib-hwstage.sh
. "$ROOT/install/lib-hwstage.sh"
hwstage_init "$ROOT"

# --- stage 1: the binaries, fetched once and cached under work/ (gitignored) ------------------
hwstage_fetch sgdisk mdir
sgdisk="$(hwstage_path sgdisk)"
mdir="$(hwstage_path mdir)"

# --- stage 2: onto the device ----------------------------------------------------------------
hwstage_ssh_opts

ssh "${SSHOPTS[@]}" "$host" 'mkdir -p /run/novadeck/probe'
scp "${SSHOPTS[@]}" -q "$sgdisk" "$mdir" "$ROOT/install/select-target.sh" "$host:/run/novadeck/probe/"
ssh "${SSHOPTS[@]}" "$host" 'chmod +x /run/novadeck/probe/sgdisk /run/novadeck/probe/mdir /run/novadeck/probe/select-target.sh'

# --- stage 3: the run ------------------------------------------------------------------------
# Markdown on stdout, per-board sections that concatenate, exactly like probe-internal.sh's
# capture — for the same reason: boards differ, so the document is a set of sections and never a
# single canonical table.
ssh "${SSHOPTS[@]}" "$host" 'bash -s' <<'REMOTE'
set -u
export PATH=/run/novadeck/probe:$PATH
ST=/run/novadeck/probe/select-target.sh

model="$( { tr -d '\0' < /sys/firmware/devicetree/base/model; } 2>/dev/null )"
echo "# select-target hardware run — ${model:-unknown board}"
echo
echo "Generated by \`install/hw-select-target.sh\` — read-only Phase 3 validation."
echo
echo '| | |'
echo '|---|---|'
echo "| Ran | $(date -u '+%Y-%m-%dT%H:%M:%SZ') |"
echo "| Board | \`${model:-?}\` |"
echo "| Kernel | \`$(uname -r)\` |"
echo "| sgdisk | \`$(sgdisk --version 2>&1 | head -1)\` |"
echo "| mdir | \`$(mdir --version 2>&1 | head -1)\` |"
for k in NOVADECK_VARIANT NOVADECK_MODE NOVADECK_VERSION NOVADECK_BUILD NOVADECK_GIT; do
  v="$(sed -n "s/^$k=//p" /etc/novadeck-release 2>/dev/null | head -1 | tr -d '"')"
  [ -n "$v" ] && echo "| $k | \`$v\` |"
done
root_src="$(findmnt -no SOURCE / 2>/dev/null | sed 's/\[.*//')"
boot_disk="$(lsblk -no PKNAME "$root_src" 2>/dev/null | head -1 | awk '{print $1}')"
echo "| Running root | \`${root_src:-?}\` |"
echo "| Boot medium — never a target | \`${boot_disk:-?}\` |"
echo

# The fact no image fixture can produce: sgdisk asks the KERNEL for the logical size, and only on
# a block device. Every offline case runs at 512 whatever the captured board reported.
echo '## Logical / physical sector size per disk'
echo
echo '| Disk | logical | physical | size |'
echo '|---|---|---|---|'
for d in /sys/block/*; do
  n="$(basename "$d")"
  case "$n" in loop*|ram*|zram*|dm-*) continue ;; esac
  printf '| `%s` | %s | %s | %s |\n' "$n" \
    "$(cat "$d/queue/logical_block_size" 2>/dev/null || echo '?')" \
    "$(cat "$d/queue/physical_block_size" 2>/dev/null || echo '?')" \
    "$(lsblk -dno SIZE "/dev/$n" 2>/dev/null | tr -d ' ' || echo '?')"
done
echo

run() {
  echo '```'
  echo "\$ select-target.sh $*"
  out="$(bash "$ST" "$@" 2>&1)"; rc=$?
  printf '%s\n' "$out"
  echo "rc=$rc"
  echo '```'
  echo
}

echo '## The scan — no argument'
echo
echo 'Rules 1, 2 and 9 reach this path and no other: the explicit-target form below cannot pick a'
echo 'disk, so it cannot exercise "never pick when two are eligible" either.'
echo
run

echo '## Every disk, named explicitly'
echo
for n in $(lsblk -dno NAME | grep -Ev '^(loop|ram|zram|dm-)'); do
  echo "### \`/dev/$n\` — $(lsblk -dno SIZE "/dev/$n" | tr -d ' ')"
  echo
  echo "PARTLABELs: \`$(lsblk -no PARTLABEL "/dev/$n" 2>/dev/null | grep -v '^$' | tr '\n' ' ')\`"
  echo
  run "/dev/$n"
done
REMOTE

echo "[novadeck] staged files remain under /run/novadeck/probe (tmpfs); they vanish at reboot" >&2
