#!/usr/bin/env bash
# Phase 0 hardware reconnaissance for the internal (UFS/eMMC) install — STRICTLY READ-ONLY.
#
# Answers the questions .claude/plans/internal-install.plan.md Phase 0 blocks on, and emits a
# markdown capture on stdout. Run it on a DEV card over SSH and keep the output:
#
#   ssh root@<device> 'bash -s' < install/probe-internal.sh > docs/internal-storage.md
#
# Dev card, because only a DEV build bakes the root authorized_keys (assemble-rootfs.sh section
# 4c) and reading a partition table needs root. A release card admits nobody as root, by design.
#
# WHY THIS EXISTS AS A SEPARATE SCRIPT, run before any installer code: the carve deletes and
# recreates Android's userdata, and its whole safety argument is that it touches that one
# partition and nothing else. That argument is written against the OEM partition names, LUN
# topology and sizes of real devices — not against recalled AOSP naming. install/disk-rules.conf
# and install/test-select-target.sh are both authored from this output, so a wrong capture here
# propagates into the deny gate that is the only thing standing between us and a hard brick
# (recoverable by EDL alone: no backups, no undo — plan §3).
#
# READ-ONLY IS THE POINT, and it is structural rather than promised:
#   - Nothing here opens a partition's CONTENTS. Everything comes from the GPT at the head of the
#     disk (sfdisk), sysfs, and udev's cached properties (lsblk). No dd, no blkid, no hexdump
#     against a partition, no mount.
#   - That is also what keeps the plan's `devinfo` invariant intact. devinfo persists the ABL boot
#     choice; the installer must never open it, and neither does this. We report its index and
#     size from GPT metadata and stop there.
#   - No tool invoked below can write. sfdisk appears only as --dump and --list-free.
#
# TOOLING: this runs on a dev card AS IT IS TODAY — no rebuild, no added packages. sgdisk would
# need gptfdisk added to the dev image first (it is one of the three packages the installer image
# must gain regardless), and needing a rebuild-and-reflash before you can inspect a device is a
# bad loop for a recon script. sfdisk --dump is the exact, restorable capture format anyway. If
# gptfdisk does land in dev builds this script picks sgdisk up opportunistically for its GUID
# view; it never requires it. Building on an absent tool is the `cmp` bug that sat dead in
# post-install.sh for three releases — see [[offline-suite-inherits-host-path]].
set -uo pipefail

[ "$(id -u)" = "0" ] || { echo "must run as root — a partition table is not readable otherwise" >&2; exit 1; }
for t in lsblk sfdisk findmnt awk sed sort; do
  command -v "$t" >/dev/null 2>&1 || { echo "$t not found in the image" >&2; exit 1; }
done

# Partitions whose CONTENTS we refuse to read, so the habit is never established. Mirrors the
# spirit of the plan's deny gate; devinfo is the one that actually matters.
HANDS_OFF='^(xbl|abl|tz|hyp|aop|devcfg|devinfo|keymaster|cmnlib|uefi|multiimgoem|storsec)'

gib()   { awk -v b="${1:-0}" 'BEGIN{ b=b+0; if (b==0) print "0"; else printf "%.2f", b/1073741824 }'; }
sysval() { cat "/sys/block/$1/$2" 2>/dev/null || echo '?'; }
# lsblk -P emits shell-quoted KEY="value" pairs, which survive empty fields and spaces in models
# where positional `read` on -r output silently shifts columns.
kv() { sed -n "s/.*[[:space:]]\{0,\}$1=\"\([^\"]*\)\".*/\1/p" <<<"$2"; }
disks() { lsblk -dno NAME,TYPE | awk '$2=="disk"{print $1}' | sort; }
# An em dash rather than an empty cell: a blank reads as "not captured" when it often means "not
# applicable to this transport" (NVMe has no HCTL).
cell() { if [ -n "${1:-}" ]; then printf '`%s`' "$1"; else printf '—'; fi; }

# The disk backing the running root. Printed loudly because every later judgement depends on not
# confusing the boot medium with an install target: select-target.sh rule 2 refuses to write the
# disk we booted from, and a reader mistaking the SD card for internal would author the deny rules
# against the wrong table.
root_src="$(findmnt -no SOURCE / 2>/dev/null | sed 's/\[.*//')"
boot_disk="$(lsblk -no PKNAME "$root_src" 2>/dev/null | head -1 | awk '{print $1}')"
[ -n "$boot_disk" ] || boot_disk='(undetermined)'

# 2>/dev/null on the redirect itself: a non-DT host has no such file, and a read-only probe has no
# business writing to stderr over it.
model="$( { tr -d '\0' < /sys/firmware/devicetree/base/model; } 2>/dev/null )"

echo "# Internal storage capture"
echo
echo "Generated by \`install/probe-internal.sh\` — read-only Phase 0 recon."
echo "Re-run and commit alongside any new board: \`install/disk-rules.conf\` is authored from this,"
echo "and \`install/test-select-target.sh\` replays the \`sfdisk --dump\` blocks below as fixtures."
echo
echo '| | |'
echo '|---|---|'
echo "| Captured | $(date -u '+%Y-%m-%dT%H:%M:%SZ') |"
echo "| Board | \`${model:-?}\` |"
echo "| Kernel | \`$(uname -r)\` |"
for k in NOVADECK_VARIANT NOVADECK_MODE NOVADECK_VERSION NOVADECK_BUILD; do
  v="$(sed -n "s/^$k=//p" /etc/novadeck-release 2>/dev/null | head -1 | tr -d '"')"
  [ -n "$v" ] && echo "| $k | \`$v\` |"
done
echo "| Running root | \`${root_src:-?}\` |"
echo "| **Boot medium — never an install target** | **\`$boot_disk\`** |"
echo

# ----------------------------------------------------------------------------- disk inventory
echo '## Disks'
echo
echo '`rm`/`ro` are the sysfs flags `select-target.sh` rule 2 gates on. WWN+HCTL are the stable'
echo 'identity — HCTL is `Host:Channel:Target:Lun`, so the UFS LUN is read off it directly rather'
echo 'than guessed from the `sdX` letter.'
echo
echo '| Disk | Role | Size | Bytes | rm | ro | HCTL (LUN) | WWN | Model |'
echo '|---|---|---|---|---|---|---|---|---|'
for d in $(disks); do
  line="$(lsblk -dPno NAME,HCTL,WWN,MODEL,SIZE "/dev/$d" 2>/dev/null | head -1)"
  bline="$(lsblk -dPbno SIZE "/dev/$d" 2>/dev/null | head -1)"
  b="$(kv SIZE "$bline")"; b="${b:-0}"
  rm_="$(sysval "$d" removable)"; ro_="$(sysval "$d" ro)"
  if [ "$d" = "$boot_disk" ]; then role='**BOOT MEDIUM**'
  elif [ "$rm_" = "1" ];        then role='removable'
  else                               role='internal candidate'
  fi
  printf '| `%s` | %s | %s GiB | %s | %s | %s | %s | %s | %s |\n' \
    "$d" "$role" "$(gib "$b")" "$b" "$rm_" "$ro_" \
    "$(cell "$(kv HCTL "$line")")" "$(cell "$(kv WWN "$line")")" "$(cell "$(kv MODEL "$line")")"
done
echo

# ----------------------------------------------------------------------------- per-disk detail
found_internal=0
for d in $(disks); do
  [ "$d" = "$boot_disk" ] && continue            # not a target; its table is noise here
  [ "$(sysval "$d" removable)" = "1" ] && continue
  found_internal=1

  echo "## \`/dev/$d\`"
  echo
  echo '### Partitions'
  echo
  echo '| # | Name (PARTLABEL) | Size | Bytes | FSTYPE | PARTUUID |'
  echo '|---|---|---|---|---|---|'
  while IFS= read -r line; do
    [ -n "$line" ] || continue
    partn="$(kv PARTN "$line")"
    [ -n "$partn" ] || continue                  # the whole-disk row
    label="$(kv PARTLABEL "$line")"
    pbytes="$(kv SIZE "$line")"; pbytes="${pbytes:-0}"
    fstype="$(kv FSTYPE "$line")"
    # FSTYPE is udev's cached probe, not a fresh read — but blank it for hands-off partitions so
    # nothing in this document even implies their contents were looked at.
    if [[ "$(tr '[:upper:]' '[:lower:]' <<<"$label")" =~ $HANDS_OFF ]]; then
      fstype='(not inspected)'
    fi
    printf '| %s | `%s` | %s GiB | %s | %s | `%s` |\n' \
      "$partn" "${label:-(unnamed)}" "$(gib "$pbytes")" "$pbytes" \
      "${fstype:-—}" "$(kv PARTUUID "$line")"
  done <<<"$(lsblk -Pbno PARTN,PARTLABEL,SIZE,FSTYPE,PARTUUID "/dev/$d" 2>/dev/null)"
  echo

  echo '### Findings'
  echo
  labels="$(lsblk -Pno PARTLABEL "/dev/$d" 2>/dev/null | sed -n 's/.*PARTLABEL="\(.*\)"$/\1/p' | tr '[:upper:]' '[:lower:]' | sed '/^$/d')"
  for want in userdata super metadata devinfo; do
    hit="$(awk -v w="$want" 'index($0,w)==1{print; exit}' <<<"$labels")"
    if [ -n "$hit" ]; then echo "- \`$want\` present (as \`$hit\`)"
    else                   echo "- \`$want\` **absent**"; fi
  done

  # userdata's real size is a product input, not just recon: the consent screen quotes it, because
  # "your Android data partition, 96.4 GiB, will be deleted" gets read where a generic warning
  # gets clicked through (plan §4d).
  udline="$(lsblk -Pbno NAME,PARTLABEL,SIZE "/dev/$d" 2>/dev/null | grep -i 'PARTLABEL="userdata' | head -1)"
  if [ -n "$udline" ]; then
    udn="$(kv NAME "$udline")"; udb="$(kv SIZE "$udline")"
    echo "- **\`userdata\` is \`/dev/$udn\` — $(gib "$udb") GiB ($udb bytes).** The one partition the carve modifies, and the figure §4d's consent screen must quote."
  else
    echo "- **No \`userdata\` on this disk** — \`require userdata\` refuses it, which is the correct outcome for a LUN that is not the Android data LUN."
  fi
  echo

  echo '### Free space'
  echo
  echo '```'
  sfdisk --list-free "/dev/$d" 2>&1 || echo '(sfdisk --list-free failed)'
  echo '```'
  echo

  # Kept verbatim rather than summarised: this is the fixture test-select-target.sh replays.
  echo '### `sfdisk --dump` (verbatim — fixture for test-select-target.sh)'
  echo
  echo '```'
  sfdisk --dump "/dev/$d" 2>&1 || echo '(sfdisk --dump failed)'
  echo '```'
  echo

  if command -v sgdisk >/dev/null 2>&1; then
    echo '### `sgdisk -p` (optional — gptfdisk present on this build)'
    echo
    echo '```'
    sgdisk -p "/dev/$d" 2>&1 || echo '(sgdisk -p failed)'
    echo '```'
    echo
  fi
done

if [ "$found_internal" = "0" ]; then
  echo '## No internal disk found'
  echo
  echo 'Every block device is either the boot medium or removable. This is itself the answer to'
  echo 'Phase 0 item 3 — **Linux does not see internal storage on this build** — and it blocks the'
  echo 'entire feature until the UFS controller comes up. `docs/bringup.md` still records UFS as'
  echo 'unverified; `CONFIG_SCSI_UFSHCD` being set is not the same thing.'
  echo
fi

cat <<'EOF'
## Still open after this capture

Answered here: LUN topology, the real OEM partition-name set, whether Linux sees internal storage,
`devinfo`'s presence and geometry, and `userdata`'s real size. Not answerable read-only from one
boot, and deliberately left out:

- **LUN enumeration stability.** Run this twice across a reboot and diff the Disks table. If a
  `sdX` name moved while its WWN/HCTL stayed put, target selection must key on WWN/HCTL.
- **ABL fallback with an absent medium** — default set to Linux/SD with no card inserted: does it
  fall back to internal, or stop? Decides whether the install flow can end at "reboot, done".
- **gamescope + gamepad with no logind session**, over `seatd` or `LIBSEAT_BACKEND=builtin`, and
  whether polkit is needed at all when the installer runs as root.
- **UFS write throughput** for a ~3.5 GB slot write, and the battery floor to refuse below. Both
  require writing, so neither belongs in a read-only probe.
EOF
